### ISSUE TITLE
kingdoms borders gone

### ISSUE THREAD

**Issue by beludiana** [breuerfelix/king-bot-api#54]
After firing up the bot (nodejs version) all the kingdom borders dissapeared permanently, even after marking kingdoms or hovering them shows the default ranges. Is just visual thing but it stuck and no idea what exactly caused it or how to fix it. Tried different browsers - same issue, if i go to new server all is fine

**Comment by didadadida93** [comment]
i'm not sure if it is related to the bot, but try to check Border Kingdom in your game settings
![Screenshot from 2019-04-29 04-26-35](https://user-images.githubusercontent.com/25358436/56870271-42531f00-6a37-11e9-9156-426dea4d19e9.png)

**Comment by beludiana** [comment]
oh ye that worked, but i can swear i never even seen this menu before, and that hapened the moment i loaded the bot for first time
