### ISSUE TITLE
NPM install "method not allowed"

### ISSUE THREAD

**Issue by aristide0511** [breuerfelix/king-bot-api#57]
Hello, I'm having a problem installing the bot. After having installed npm from apt and cloned the repo, i get this error when running npm install:

`pi@raspberrypi:~/Travian/king-bot-api $ npm install
(node:8044) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.98-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/Travian/king-bot-api
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Travian/king-bot-api/npm-debug.log
npm ERR! not ok code 0
`
Has anyone encountered this before? I'm running it on a raspberry pi

**Comment by raj-aayush** [comment]
Have you managed to fix this issue? If so, could you write a response to this detailing how you managed to do so?

**Comment by aristide0511** [comment]
Had to install nodeJS completely, not just npm
