### ISSUE TITLE
Raise fields bug with insta finish

### ISSUE THREAD

**Issue by Grady99** [breuerfelix/king-bot-api#60]
After setting to upgrade fields to lvl 5 (they were level from 1 to 3) it stopped working halfway through. It insta finished the field but did not build the next one. I turned the option off and on again and it started working again.

Screen of logger: 
![image](https://user-images.githubusercontent.com/49346041/61575838-573ccd00-aad1-11e9-830e-6a3cfdf7914f.png)

**Comment by OneManDevz** [comment]
This happens to me, often.
The cause of this problem (at least for me, and few of my fellow players) is that if you have a sitter/dual and he log in on you acc, the feature will stop. And if you log in different browser/IP.

**Comment by Grady99** [comment]
For my case, no one was on my account but me, so no log ins from other IPs

**Comment by breuerfelix** [comment]
did it stop at all ? or did it just have some longer delays ?

**Comment by Grady99** [comment]
Uh, that's a long time ago, but if I remember correctly, I think it would start building after some time. I think the problem was that even though the time was <5 min, it didn't insta finish and would wait instead.
