### ISSUE TITLE
Modify and create farmlist

### ISSUE THREAD

**Issue by Sergi-Olas** [breuerfelix/king-bot-api#63]
It would be a good option to be able to edit and modify the farmlist.
For example, being able to remove villages that were added some time ago or have one list for cows and other for active people that we are controlling.
I'm sorry if this option already exists and I haven't found it

**Comment by OneManDevz** [comment]
Is it necessary if this is already implemented in the game itself?

**Comment by breuerfelix** [comment]
i would also close this issue since the game already implemented this feature :)  
i would focus on things which are not possible in the game right now :)
