### ISSUE TITLE
Error with Building queue feature

### ISSUE THREAD

**Issue by krumfi** [breuerfelix/king-bot-api#66]
Hi,
I can't use building queue cause  => "Couldn't find village"

**Comment by OneManDevz** [comment]
Did you rename the village in-game? If so you gotta open the bot and choose
the new name.

Dňa po 23. 9. 2019, 23:33 krumfi <notifications@github.com> napísal(a):

**Comment by krumfi** [comment]
i didn't change the name since i got the bot
no one of my 5 villages work

**Comment by raj-aayush** [comment]
The refactored code should have fixed this issue of village_name breaking the bot. Have you pulled the latest code commit and tried to run the bot on that?

**Comment by krumfi** [comment]
i get the bot the 2019-09-23 00:14 via releases and launch the .exe file.
But i will clone the repository for try ;)

i just got this in the electron logs
you may want the console error ?
![botError](https://user-images.githubusercontent.com/16351052/65551437-402bb880-df22-11e9-8d78-d8dac616eb2f.PNG)

**Comment by OneManDevz** [comment]
Sometimes the bot fails, like stops (at least for me). Do you have a
console output?

Dňa ut 24. 9. 2019, 23:32 krumfi <notifications@github.com> napísal(a):

**Comment by krumfi** [comment]
Ok, it's work with cloning and running project
maybe something to install for the windowsX64 release ?

Tell me if i can close this issue
Thx a lot <3

**Comment by raj-aayush** [comment]
The latest release is still a work in progress and once more features are added, we might work on one. Glad this issue got resolved! :)
