### ISSUE TITLE
[Errno 122] Disk quota exceeded

### ISSUE THREAD

**Issue by Anonkali** [breuerfelix/king-bot-api#76]
What does this mean and how do i fix it?  I'm attempting to use the Inactive farm finder.

**Comment by umtaaka7** [comment]
i also take this alert "[Errno 122] Disk quota exceeded" how can fix it.

**Comment by breuerfelix** [comment]
the problem is on my server... i got this service running on a service of mine, and i need to migrate it to my new server :) i will do this until monday ! hopefully tomorrow :) i will let you know once i finished this

**Comment by breuerfelix** [comment]
should be working again :)
