### ISSUE TITLE
access bot runing in cloud

### ISSUE THREAD

**Issue by leourl** [breuerfelix/king-bot-api#77]
i managed to make it run on a ubuntu server in amazon, how do i open the localhost:3000 to access from the internet?

i tried ip_adress:3000, it wont work

please help

**Comment by OneManDevz** [comment]
Have you tried accessing the bot via server's DNS name?
![image](https://user-images.githubusercontent.com/42937562/70813739-49624e00-1dca-11ea-8f40-5458277b4a74.png)
Have you allowed the port (on which the bot is running) to public? 
![image](https://user-images.githubusercontent.com/42937562/70813904-9ba36f00-1dca-11ea-933a-6b4a7a9c09ca.png)

**Comment by leourl** [comment]
can u be more specific? i'm pretty new at this, srry

**Comment by OneManDevz** [comment]
I had a server in azure.
There I needed to set used ports to be open to public.
Not sure with ubuntu but this might help you
https://www.cyberciti.biz/faq/how-to-open-firewall-port-on-ubuntu-linux-12-04-14-04-lts/
And also this link is for AWS. This should be more suitable for you.
https://community.spiceworks.com/topic/1331302-allowing-a-specific-amazon-web-services-server-communicate-through-firewall

**Comment by OneManDevz** [comment]
Or better this:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html
